### ISSUE TITLE
flask_restless and possibility to client to define columns he want to get

### ISSUE THREAD

**Issue by ddurieux** [talaos/talaos-inventory#2]
For example if asset display only id + name, and client want comment field, client use http://.../api/asset?cols=id,name,comment

There is a commit + pull request in restless but failed unit tests, see https://github.com/jfinkels/flask-restless/pull/326

Perhaps fix it to have it in restless code ;)

**Comment by kiniou** [comment]
Closing since flask-restless is no longer relevant to this project.
